### ISSUE TITLE
Feature Request: Notification counter

### ISSUE THREAD

**Issue by trunneml** [GuMiner/garmin-simple-clarity#1]
Hi, is it possible to add a notification indicator or counter? Would be realy awesome

**Comment by GuMiner** [comment]
I can add this in along with an indicator when the device is connected to the phone. I will have an update here today and an update to the app on the Connect IQ site by tomorrow (https://apps.garmin.com/en-US/apps/2720a7b1-cb76-47b5-8577-e7c96edd2888, pending review time).

**Comment by GuMiner** [comment]
That was quicker than I expected. The application has been updated and is available from the Garmin Connect IQ store.

**Comment by trunneml** [comment]
Wow! So awesome! Thank you!
Did you try to place the indicators on the bottom? There is more empty room, and that area is easier to look at without moving the arm. :-)

**Comment by GuMiner** [comment]
I've created a [new issue](https://github.com/GuMiner/garmin-simple-clarity/issues/2) to track that work. I haven't used the settings API yet, so this will take more time because I want to make the positioning configurable.
